language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "4.4"
  - "5.11"
  - "6.1"
 
script:
  - "npm test;"
  - "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

env:
  matrix:
    - COVERAGE=1

sudo: false
